spring:
  application:
    name: supermarket
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/supermarket}
    username: ${DB_USER:supermarket}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
